### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by ojura**
I've merged some upstream commits here. Also, since the API changed (googlecartographer/cartographer#269), I decided to remove your SparsePoseGraph::GetSubmapTransforms(), and to modify MapBuilderBridge::GetConstraintsList() to call the new version from upstream, SparsePoseGraph::GetSubmapTransforms(trajectory), for all trajectories.

### CODE REVIEW

**Comment by ojura** [comment]
Also have a look at my comment in googlecartographer/cartographer#261, SparsePosegraph::constraints() needs to be public.

**Comment by jihoonl** [comment]
Thanks @ojura. I am preparing a new PR with a clean branch. I will apply the changes that you suggested in this PR.

**Comment by ojura** [comment]
Sure. Although, the Cartographer guys always squash the pull request when merging. If you're making a completely new branch just to have a cleaner tree for them, it will all get squashed into one commit anyway, so all these ugly merge commits won't be a problem :)

**Comment by jihoonl** [comment]
I see ok . Thanks.

**Pull request merged**
